name: Test MAT-MEK4270 projects

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Test with pytest
      run: |
        cd projects
        uv run pytest decay_v3.py mesh_function.py differentiate.py VibFD.py Wave1D.py

